import { Inter } from "next/font/google";  // Only import Inter
import '../styles/globals.css';  // Import Tailwind and general global styles

// Load the Inter font from Google Fonts
const interSans = Inter({
  variable: "--font-inter-sans",  // Rename to match standard font naming
  subsets: ["latin"],
});

// Use the same font for a mono variant
const interMono = Inter({
  variable: "--font-inter-mono",  // Same font, but for mono variant
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${interMono.variable} antialiased`}  // Apply font classes correctly
      >
        {children}
      </body>
    </html>
  );
}
